steps:
  # see https://www.npmjs.com/package/editorconfig-checker

  - name: "ubuntu"
    args: ['bash', './test/doc-check.sh']

#   name: "gcr.io/cloud-builders/go"
#   args: ["build"]
#   env: ["GOPATH=.","GO111MODULE=on", "CGO_ENABLED=0"]
# - id: go_test
#   name: "gcr.io/cloud-builders/go"
#   args: ["test","helloworld"]
#   env: ["GOPATH=."]  
